Repository kubernetes-sigs/apisnoop, pull requests merged in 2019-05, with the labels that each got.

#204 Update readme
  README.md
  data-gen/downloadArtifacts.py
  data-gen/processArtifacts.py
  data-gen/snoopAuditlog.py
  data-gen/sources.yaml
  data-gen/updateSources.py
Labels: approved, do-not-merge/release-note-label-needed, size/L

#201 Aesthetic appeal
  .gitignore
  app/app.org
  app/public/audit-sources.yaml
  app/public/stylesheet.css
  app/src/bundles/bucket-list.js
  app/src/bundles/filters.js
  app/src/bundles/index.js
  app/src/bundles/job-results-metadata.js
  app/src/bundles/metadata.js
  app/src/bundles/test-tags.js
  app/src/bundles/tested-stats.js
  app/src/bundles/tests.js
  app/src/bundles/useragents.js
  app/src/components/active-filter.js
  app/src/components/active-tests-list.js
  app/src/components/bucket-list.js
  app/src/components/filter-container.js
  app/src/components/filters-container.js
  app/src/components/header.js
  app/src/components/search-bar.js
  app/src/components/search-results.js
  app/src/components/summary-container.js
  app/src/components/sunburst-header.js
  app/src/components/test-tags-list.js
  app/src/components/tests-filter-container.js
  app/src/components/tests-search-container.js
  app/src/components/useragents-search-container.js
  app/src/lib/utils.js
  app/src/pages/main-page.js
  audit-sources.yaml
Labels: approved, do-not-merge/release-note-label-needed, lgtm, size/XXL

#206 Docs: Adding auditlog support for CNF Tesbed
  docs/auditlogs/cnf-tesbed.org
Labels: approved, do-not-merge/release-note-label-needed, lgtm, size/L

#205 Fixing python version related to yaml loading
  README.md
  apisnoop.sh
  audit-sources.yaml
  data-gen/downloadArtifacts.py
  data-gen/processArtifacts.py
  data-gen/sources.yaml
  data-gen/updateSources.py
Labels: approved, do-not-merge/release-note-label-needed, size/L

#208 Aesthetic improvement
  app/app.org
  app/src/bundles/bucket-list.js
  app/src/bundles/sunburst.js
  app/src/bundles/tested-stats.js
  app/src/components/active-tests-list.js
  app/src/components/test-tags-search-container.js
  app/src/components/tests-filter-container.js
  app/src/components/tests-search-container.js
  app/src/components/useragents-search-container.js
Labels: approved, do-not-merge/release-note-label-needed, size/L

#209 Update readme
  docs/images/apisnoop.png
  docs/images/filters.png
  docs/images/test_sequence.png
Labels: approved, do-not-merge/release-note-label-needed, lgtm, size/XS

#219 Add data exploration
  data-gen/explore.org
Labels: approved, do-not-merge/release-note-label-needed, size/L

#227 Adding netlify.toml
  netlify.toml
Labels: approved, do-not-merge/release-note-label-needed, size/M

#236 adding file on Tue May 7 22:45:38 UTC 2019
  file
Labels: approved, size/XS

#233 buckets and filters in sidebar
  app/app.org
  app/public/stylesheet.css
  app/src/bundles/bucket-list.js
  app/src/components/bucket-list.js
  app/src/components/endpoint-categories.js
  app/src/components/filter-container.js
  app/src/components/filters-container.js
  app/src/components/footer.js
  app/src/components/header.js
  app/src/components/search-bar.js
  app/src/components/search-results.js
  app/src/components/sidebar.js
  app/src/components/sunburst-and-summary.js
  app/src/pages/main-page.js
Labels: approved, size/L

#241 Logo and Reset button in Sidebar, Better styling on filters, maintain filters when bucket changes, add legend
  app/app.org
  app/package-lock.json
  app/public/assets/github-logo-white.png
  app/src/bundles/filters.js
  app/src/bundles/index.js
  app/src/bundles/sunburst.js
  app/src/bundles/useragents.js
  app/src/components/active-filter.js
  app/src/components/app.js
  app/src/components/bucket-list.js
  app/src/components/filter-container.js
  app/src/components/filter-reset-button.js
  app/src/components/filters-container.js
  app/src/components/footer.js
  app/src/components/legend.js
  app/src/components/search-results.js
  app/src/components/sidebar.js
  app/src/components/sunburst-and-summary.js
  app/src/components/sunburst-header.js
  app/src/components/sunburst.js
  app/src/components/tests-container.js
  app/src/pages/main-page.js
Labels: UX/UI, WebApp, approved, size/XL

#249 Do not generate data unless sources or methods change
  hack/ci/netlify-pr.sh
  hack/ci/netlify-production.sh
  hack/ci/prow-pr.sh
Labels: approved, lgtm, size/L

#245 toggle sunburst to untested, tested, and/or conformance-tested only
  app/app.org
  app/src/bundles/endpoints.js
  app/src/components/sunburst-container.js
  app/src/components/tested-toggle.js
Labels: approved, lgtm, size/L

#248 Endpoint list
  app/app.org
  app/src/bundles/bucket-list.js
  app/src/components/bucket-list.js
  app/src/components/endpoint-list-entry.js
  app/src/components/endpoints-list.js
  app/src/components/filter-container.js
  app/src/components/legend.js
  app/src/components/tested-toggle.js
  app/src/pages/main-page.js
Labels: WebApp, approved, lgtm, size/L
