Repository kubernetes-sigs/apisnoop, pull requests merged in 2020-10, with the labels that each got.

#393 Update docker file to allow postgres to own the /var/lib files
  apps/snoopdb/postgres/Dockerfile
Labels: size/XS

#392 Kind
  kind/.dir-locals.el
  kind/audit/policy.yaml
  kind/audit/sink.yaml
  kind/kind+apisnoop.yaml
  kind/manifests/apisnoop.yaml
  kind/readme.org
Labels: size/L

#397 Locate missing event related e2e test coverage
  org/explorations/missing_events.md
  org/explorations/missing_events.org
  org/explorations/namespace_hit_check.md
  org/explorations/namespace_hit_check.org
Labels: size/XXL
