Repository kubernetes-sigs/apisnoop, pull requests merged in 2020-04, with the labels that each got.

#309 Add roadmap that includes Q2 OKRs and status on Q1 OKRs
  org/roadmap.md
  org/roadmap.org
Labels: size/L

#311 Q1 OKR Coverage OKR Score 0.3 -> 0.4
  org/roadmap.org
Labels: size/S

#312 Add final Q1 numbers and ensure presentation exports
  org/roadmap.md
  org/roadmap.org
Labels: size/L

#313 add some clarifying notes to q2 okr's
  org/roadmap.org
Labels: lgtm, size/XS

#314 Q2 OKR Update - Team Review
  org/roadmap.html
  org/roadmap.md
  org/roadmap.org
  org/roadmap.txt
Labels: size/XL

#315 Docs and helpers
  docs/overview.org
  docs/setup-with-kubemacs.org
  kubemacs.env
  kubemacs.sh
  org/archive/meta.org
  org/archive/meta_bot.org
  org/archive/tables_and_views.org
  org/archive/webapp.org
  org/explorations/find-replace-fun.org
  org/tables_and_views.org
Labels: size/XXL

#317 Kleinhans
  tickets/k8s/CoreV1NodeStatus.org
  tickets/k8s/KleinhansTestTicket.md
  tickets/k8s/KleinhansTestTicket.org
Labels: size/XL

#320 Check that my first apisnoop pr and test issue have been created
  tickets/k8s/CoreV1NodeStatus.md
  tickets/k8s/CoreV1NodeStatus.org
  tickets/k8s/KleinhansTestTicket.org
Labels: size/L

#299 Add WIP ServiceAccount Resource Lifecycle test
  org/tickets/CoreV1ServiceAccountResourceLifecycleTest.md
  org/tickets/CoreV1ServiceAccountResourceLifecycleTest.org
Labels: size/XL

#326 Create Mock Test for deleteCoreV1CollectionNamespacedEvent
  tickets/k8s/deleteCoreV1CollectionNamespacedEventTest.org
Labels: size/L

#328 Fixed cmd order for copy paste
  docs/ZachCalebTestWritingTutorialNotes.org
Labels: size/XS
