Repository kubernetes-sigs/apisnoop, pull requests merged in 2020-11, with the labels that each got.

#405 Instructions for getting up gcb test environmet
  org/config-gcb-env.org
Labels: size/L

#407 testing adding coverage diff Tue Nov 3 04:13:21 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XXL

#410 Prettiest json
  apps/snoopdb/postgres/initdb/308_fn_generate_latest_coverage_json.sql
  apps/snoopdb/postgres/initdb/505_output_coverage_jsons.sql
  apps/snoopdb/tables-views-functions.org
  org/tickets/single-endpoint-stable-groups.org
  resources/coverage/1.20.0.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XL

#413 at1 adding the NEW AND IMPROVED coverage diff Thu Nov 5 20:32:57 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-endpoints.json
Labels: size/XXL

#414 at1 adding the NEW AND IMPROVED coverage diff Thu Nov 5 21:41:54 UTC 2020
  resources/coverage/1.20.0.json
Labels: size/S

#416 at2 adding the NEW AND IMPROVED coverage diff Fri Nov 6 02:13:28 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-endpoints.json
Labels: size/L

#417 at2 adding the NEW AND IMPROVED coverage diff Fri Nov 6 02:30:30 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/L

#419 at4 adding the NEW AND IMPROVED coverage diff Fri Nov 6 02:49:50 UTC 2020
  resources/coverage/1.20.0.json
Labels: size/XS

#420 at5 adding the NEW AND IMPROVED coverage diff Fri Nov 6 03:01:53 UTC 2020
  resources/coverage/1.20.0.json
Labels: size/XS

#430 Changes in coverage diff Mon Nov 16 23:44:16 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/L

#431 Changes in coverage diff Tue Nov 17 00:09:02 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XXL

#432 Changes in coverage diff Thu Nov 19 19:42:10 UTC 2020
  resources/coverage/1.20.0.json
Labels: size/XS

#433 Changes in coverage diff Thu Nov 19 21:38:51 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/L

#434 Changes in coverage diff Thu Nov 19 21:48:50 UTC 2020
  resources/coverage/1.20.0.json
Labels: size/XS

#435 Changes in coverage diff Thu Nov 19 22:53:44 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XL

#436 Changes in coverage diff Mon Nov 23 19:12:15 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-endpoints.json
Labels: size/L

#437 Changes in coverage diff Mon Nov 23 20:03:55 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/L

#438 Changes in coverage diff Mon Nov 23 20:40:11 UTC 2020
  resources/coverage/1.20.0.json
Labels: size/XS

#439 Changes in coverage diff Mon Nov 23 21:39:12 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XL

#440 Changes in coverage diff Mon Nov 23 22:32:16 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/L

#441 Changes in coverage diff Tue Nov 24 01:30:26 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/L

#443 Final roadmap1.20
  docs/index.html
  docs/roadmap-1.20.html
  docs/roadmap-1.20.org
Labels: size/XL

#444 Changes in coverage diff Tue Nov 24 16:43:13 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/L

#445 Revert coverage to state at PR #435
  resources/coverage/1.20.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XL

#446 Changes in coverage diff Tue Nov 24 20:03:34 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XL

#447 Changes in coverage diff Tue Nov 24 22:05:21 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-endpoints.json
Labels: size/L

#448 Changes in coverage diff Mon Nov 30 16:58:10 UTC 2020
  resources/coverage/1.20.0.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/L
