Repository kubernetes-sigs/apisnoop, pull requests merged in 2020-05, with the labels that each got.

#331 Update current progress with k/k issue #90619
  tickets/k8s/deleteCoreV1CollectionNamespacedEventTest.org
Labels: size/XS

#330 Create Mock Test for deleteCoreV1CollectionNamespacedPod
  tickets/k8s/deleteCoreV1CollectionNamespacedPodTest.org
Labels: size/L

#332 Update current progress with k/k issue #90663
  tickets/k8s/deleteCoreV1CollectionNamespacedPodTest.org
Labels: size/XS

#334 Create Mock Test for deleteCoreV1CollectionNamespacedPodTemplate
  tickets/k8s/deleteCoreV1CollectionNamespacedPodTemplateTest.org
Labels: size/L

#329 Add Docker Prune tips
  docs/toolsTipsAndTricks.org
Labels: size/S

#321 Add links to mock-test template.org
  tickets/k8s/mock-template.org
Labels: size/XS

#333 Add endpoints not to test doc
  apps/hasura/index.org
  tickets/k8s/EndpointsToNotTest.org
Labels: size/L

#289 Add WIP ReplicationController lifecycle test - +7 test endpoint coverage
  org/tickets/CoreV1ReplicationController.md
  org/tickets/CoreV1ReplicationController.org
Labels: k8s, size/XL

#323 K8s watch events test tooling
  tickets/k8s/watch-events-tooling.md
  tickets/k8s/watch-events-tooling.org
Labels: k8s, size/L

#337 Show Percentage of conformance coverage for eligible endpoints
  apps/hasura/app/migrations/520_view_stable_endpoint_stats.up.sql
  apps/hasura/index.org
  apps/webapp/app/src/components/CoverageOverTime/Graph.svelte
  apps/webapp/app/src/components/CoverageOverTime/Prologue.svelte
  apps/webapp/app/src/queries/index.js
  apps/webapp/index.org
  kustomize/webapp-patch.yaml
  tickets/apisnoop/335_plus_16_endpoints_cot_graph.org
  tickets/apisnoop/apisnoop.cncf.io.org
Labels: size/L

#318 Mock Test -> Ginkgo Test Capabilities
  org/explorations/find-replace-fun.org
  org/explorations/replace_errs_in_mock_template.org
  tickets/k8s/.dir-locals.el
  tickets/k8s/CoreV1NodeStatus.org
  tickets/k8s/mock-template.org
Labels: size/XXL

#339 May APISnoop News Update
  org/roadmap-archive.org
  org/roadmap.html
  org/roadmap.md
  org/roadmap.org
  org/roadmap.txt
  tickets/k8s/.dir-locals.el
Labels: size/XXL
