Repository kubernetes-sigs/apisnoop, pull requests merged in 2021-04, with the labels that each got.

#500 Ticket 497
  apps/snoopdb/postgres/initdb/103_table_ineligible_endpoint.sql
  apps/snoopdb/postgres/initdb/300_fn_load_open_api.sql
  apps/snoopdb/postgres/initdb/301_fn_load_audit_events.sql
  apps/snoopdb/postgres/initdb/309_fn_grab_past_releases.sql
  apps/snoopdb/postgres/initdb/310_fn_generate_latest_coverage_json.sql
  apps/snoopdb/postgres/initdb/500_load_all_open_api.sql
  apps/snoopdb/tables-views-functions.org
  apps/web/package-lock.json
  apps/web/package.json
  apps/web/src/App.svelte
  apps/web/src/components/Sunburst/Prologue.svelte
  apps/web/src/lib/constants.js
  apps/web/src/main.js
  apps/web/src/pages/About.svelte
  apps/web/src/pages/Home.svelte
  apps/web/src/store/index.js
  docs/updating_apisnoop_upon_a_new_release.org
  org/tickets/497_update-releases.org
  resources/coverage/1.22.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XXL

#501 Ticket 497
  505_output_coverage_jsons.sql
  apps/snoopdb/postgres/initdb/503_load_ineligible_endpoints.sql
  apps/snoopdb/postgres/initdb/504_refresh_eligible_endpoint_coverage.sql
  apps/snoopdb/postgres/initdb/505_output_untested_endpoints.sql
  apps/snoopdb/postgres/initdb/506_output_coverage_jsons.sql
  apps/snoopdb/tables-views-functions.org
Labels: size/S

#502 Bump snoopdb img for cloudbuild
  cloudbuild.yaml
Labels: size/XS

#503 bump image in snoopdb helm chart
  charts/snoopdb/Chart.yaml
Labels: lgtm, size/XS

#496 Roadmap file for end of 1.21
  docs/roadmap-1.21.html
  docs/roadmap-1.21.md
  docs/roadmap-1.21.org
Labels: size/L
