Repository kubernetes-sigs/apisnoop, pull requests merged in 2021-03, with the labels that each got.

#473 Changes in coverage diff Tue Mar 2 23:54:54 UTC 2021
  resources/coverage/1.21.0.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/L

#475 Server free app
  apps/web/.gitignore
  apps/web/README.md
  apps/web/package-lock.json
  apps/web/package.json
  apps/web/public/favicon.png
  apps/web/public/global.css
  apps/web/public/index.html
  apps/web/public/logo-192.png
  apps/web/public/logo-512.png
  apps/web/public/logo.png
  apps/web/rollup.config.js
  apps/web/scripts/setupTypeScript.js
  apps/web/src/App.svelte
  apps/web/src/components/Nav.svelte
  apps/web/src/components/SectionHeader.svelte
  apps/web/src/components/Sunburst/Breadcrumb.svelte
  apps/web/src/components/Sunburst/EndpointStats.svelte
  apps/web/src/components/Sunburst/Graph.svelte
  apps/web/src/components/Sunburst/Prologue.svelte
  apps/web/src/components/Sunburst/Stats.svelte
  apps/web/src/components/Sunburst/Wrapper.svelte
  apps/web/src/components/conformance-endpoints-filter.svelte
  apps/web/src/components/conformance-endpoints-table.svelte
  apps/web/src/components/icons/link-solid.svelte
  apps/web/src/components/new-endpoints.svelte
  apps/web/src/components/vega-charts/coverage-by-release.svelte
  apps/web/src/components/vega-charts/stable-coverage-at-release.svelte
  apps/web/src/lib/colours.js
  apps/web/src/lib/constants.js
  apps/web/src/main.js
  apps/web/src/pages/About.svelte
  apps/web/src/pages/Home.svelte
  apps/web/src/pages/conformance-progress/Endpoints.svelte
  apps/web/src/pages/conformance-progress/Index.svelte
  apps/web/src/pages/conformance-progress/IneligibleEndpoints.svelte
  apps/web/src/store/conformance.js
  apps/web/src/store/index.js
  org/tickets/474_server-free-web-app.org
  todo.org
Labels: size/XXL

#478 Env var switch
  apps/web/package-lock.json
  apps/web/package.json
  apps/web/rollup.config.js
  apps/web/src/lib/constants.js
Labels: size/M

#481 Change Bazel version from 3.0.0 to 3.4.1
  org/config-gcb-env.org
Labels: size/XS

#482 Changes in coverage diff Tue Mar 9 17:42:50 UTC 2021
  resources/coverage/1.21.0.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XL

#483 Changes in coverage diff Wed Mar 10 14:52:51 UTC 2021
  resources/coverage/1.21.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XXL

#485 Changes in coverage diff Thu Mar 11 14:10:50 UTC 2021
  resources/coverage/1.21.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XL

#487 Update March data for Roadmap
  docs/roadmap-1.21.html
  docs/roadmap-1.21.md
  docs/roadmap-1.21.org
Labels: size/L

#489 Changes in coverage diff Mon Mar 15 20:36:49 UTC 2021
  resources/coverage/1.21.0.json
  resources/coverage/conformance-endpoints.json
Labels: size/XL

#491 Changes in coverage diff Wed Mar 17 00:34:42 UTC 2021
  resources/coverage/1.21.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XXL

#493 Changes in coverage diff Mon Mar 22 22:41:35 UTC 2021
  resources/coverage/1.21.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XL

#495 Changes in coverage diff Mon Mar 29 01:31:30 UTC 2021
  resources/coverage/1.21.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XL
