Repository kubernetes-sigs/apisnoop, pull requests merged in 2021-06, with the labels that each got.

#508 fix sorting logic for consistent release switcher
  apps/web/src/components/Sunburst/Prologue.svelte
  apps/web/src/pages/Home.svelte
  apps/web/src/store/index.js
  org/tickets/506_switching-releases.org
Labels: size/M

#511 fix bizarre graph behaviour when filtering to conformance only on home page
  apps/web/src/components/Sunburst/ConformanceToggle.svelte
  apps/web/src/store/index.js
Labels: size/S

#512 Changes in coverage diff Mon Jun 14 00:16:00 UTC 2021
  resources/coverage/1.22.0.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/L

#513 Changes in coverage diff Wed Jun 16 21:12:22 UTC 2021
  resources/coverage/1.22.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XL

#514 Changes in coverage diff Wed Jun 16 22:00:16 UTC 2021
  resources/coverage/1.22.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XL

#515 Changes in coverage diff Thu Jun 17 11:09:52 UTC 2021
  resources/coverage/1.22.0.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/L
