Repository kubernetes-sigs/apisnoop, pull requests merged in 2022-06, with the labels that each got.

#552 Update snoop .json files
  resources/coverage/1.25.0.json
  resources/coverage/conformance-endpoints.json
Labels: size/L

#553 Update snoop .json files
  resources/coverage/1.25.0.json
Labels: size/M

#555 Add auto updating for coverage
  .github/workflows/updater.yml
Labels: size/M

#556 Update the coverage updater
  .github/workflows/updater.yml
Labels: size/XS

#557 Use wait for psql until generating coverage
  .github/workflows/updater.yml
Labels: size/XS

#559 Fix snoopdb typo in coverage updater
  .github/workflows/updater.yml
Labels: size/XS

#565 Scheduler update on 12:00 Saturdays
  .github/workflows/updater.yml
Labels: size/XS
