Repository kubernetes-sigs/apisnoop, pull requests merged in 2022-05, with the labels that each got.

#543 W18 2022 update .json files
  resources/coverage/1.24.0.json
  resources/coverage/conformance-endpoints.json
Labels: size/M

#544 Update release to 1.25.0
  505_output_coverage_jsons.sql
  resources/coverage/releases.yaml
Labels: size/XS, do-not-merge/hold

#545 update snoop to include 1.25
  resources/coverage/1.25.0.json
  resources/coverage/conformance-endpoints.json
Labels: size/M

#547 update snoop .json files
  resources/coverage/1.25.0.json
  resources/coverage/conformance-endpoints.json
Labels: size/S

#542 Graceful snoop
  apps/snoopdb/postgres/initdb/101_table_audit_event.sql
  apps/snoopdb/postgres/initdb/301_fn_load_audit_events.sql
  apps/snoopdb/postgres/snoopUtils.py
  apps/snoopdb/postgres/snooputils_test.py
  apps/snoopdb/postgres/testdata/audit-kind-page.html
  apps/snoopdb/postgres/testdata/audit_event.json
  apps/snoopdb/postgres/testdata/audit_event_bad_verb.json
  apps/snoopdb/postgres/testdata/audit_event_dummy_request.json
  apps/snoopdb/postgres/testdata/audit_event_part_count_too_high.json
  apps/snoopdb/postgres/testdata/bad_audit_event.json
  apps/snoopdb/tables-views-functions.org
  org/explorations/better-error-handling.org
  org/tickets/540_graceful-snoop.org
Labels: size/XL

#549 Update snoop .json files
  resources/coverage/1.25.0.json
  resources/coverage/conformance-endpoints.json
Labels: size/XXL

#550 Update snoop .json files
  resources/coverage/1.25.0.json
  resources/coverage/conformance-endpoints.json
Labels: size/M

#551 Update snoop .json files
  resources/coverage/1.25.0.json
  resources/coverage/conformance-endpoints.json
Labels: size/M
