Repository kubernetes-sigs/apisnoop, pull requests merged in 2024-12, with the labels that each got.

#913 chore: update coverage for 2024-12-01-19-27
  resources/coverage/1.32.0.json
Labels: size/XS, lgtm, approved, cncf-cla: yes

#915 chore: update conformance runs url
  apps/snoopdb/postgres/Dockerfile
  apps/snoopdb/postgres/snoopUtils.py
Labels: lgtm, size/S, approved, cncf-cla: yes

#916 chore: update weekly updater image to 20241203
  .github/workflows/apisnoop_weekly_updater.yml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#918 chore: update coverage for 2024-12-03-21-22
  resources/coverage/1.32.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: lgtm, approved, size/XL, cncf-cla: yes

#920 chore: use kubernetes-ci-logs in more places
  README.org
  apps/snoopdb/postgres/initdb/301_fn_load_audit_events.sql
  apps/web/src/components/Sunburst/Prologue.svelte
  apps/web/src/pages/About.svelte
Labels: size/XS, lgtm, approved, cncf-cla: yes

#922 Add Kubermatic to OWNERS and SECURITY_CONTACTS
  OWNERS
  SECURITY_CONTACTS
Labels: size/XS, lgtm, approved, cncf-cla: yes

#923 chore: update coverage for 2024-12-07-12-05
  resources/coverage/1.32.0.json
  resources/coverage/conformance-endpoints.json
Labels: size/L, lgtm, approved, cncf-cla: yes

#924 Update stable.txt url
  cmd/update-kubernetes-release-version/main.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#925 update Kubernetes version for 2024-12-13-04-15
  resources/coverage/releases.yaml
Labels: size/XS, approved, cncf-cla: yes

#926 chore: update coverage for 2024-12-13-11-38
  resources/coverage/1.32.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
Labels: size/XXL, lgtm, approved, cncf-cla: yes
