Repository kubernetes-sigs/apisnoop, pull requests merged in 2025-09, with the labels that each got.

#957 Better detection of latest successful build
  apps/snoopdb/postgres/snoopUtils.py
Labels: lgtm, approved, size/M, cncf-cla: yes

#961 adjust for kubetest2 generated finished.json
  apps/snoopdb/postgres/snoopUtils.py
Labels: size/XS, lgtm, approved, cncf-cla: yes

#959 chore: update coverage for 2025-09-01-07-51
  resources/coverage/1.35.0.json
  resources/coverage/conformance-coverage-per-release.json
  resources/coverage/conformance-endpoints.json
  resources/coverage/conformance-progress.json
  resources/coverage/ineligible_endpoints.json
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#964 Switch to newer structure of links for KGCL log files
  apps/snoopdb/postgres/snoopUtils.py
Labels: lgtm, size/S, approved, cncf-cla: yes

#968 chore: update coverage for 2025-09-22-06-34
  resources/coverage/1.35.0.json
  resources/coverage/conformance-endpoints.json
Labels: lgtm, approved, size/M, cncf-cla: yes
